name: Restaurar entorno renv
on: [push]  

jobs:
  renv_restore:
    runs-on: ubuntu-latest  # Usa un runner de GitHub Actions con Ubuntu
    steps:
      - uses: actions/checkout@v3        # 1. Descarga el código del repositorio
      - uses: r-lib/actions/setup-r@v2   # 2. Instala R en el runner
      - uses: r-lib/actions/setup-renv@v2  # 3. Instala {renv} y restaura paquetes automáticamente
      - name: Comprobar estado de renv
        run: Rscript -e "renv::status()"  # 4. (Opcional) Verifica que el entorno esté sincronizado
